### ISSUE TITLE
GUI error?

### ISSUE THREAD

**Issue by hookerjsva** [ServiceNow/devtraining-needit-madrid#110]
Hello,

Where can I submit a bug report for the service now GUI?

Release M.11.25 (Madrid)

Attempting to assign a task to someone from a list report on a dashboard.  When you are further down the list the dialog for replacement entry is created even further very far down the page.

I may have found a possible solution as well.

DIV "cell_edit_window" is currently a child of
"grid-stack-container"

it should be a child under
"grid-widget-content"

which is nested under the following DIVs in the document body

sn-canvas-main
dash-body
sn-canvas-left
sn-canvas-left-content
grid-stack-container
(currently here)
grid-stack
grid-stack-item
grid-stack-item-content
grid-widget-content
(should be anywhere under this in the DOM inside a positioned element to prevent reverting to body)

**Comment by niedziel** [comment]
You can report bugs to our Customer Support team:  https://www.servicenow.com/support/contact-support.html.
